package:
  name: snapshot
  version: "{{ load_setup_py_data().version }}"
source:
  #    git_tag: 0.9.1
  #    git_url: https://github.com/channelaccess/snapshot.git
  path: ..

requirements:
  build:
    - python
    - setuptools
    - pyqt
    - pyepics
  run:
    - python
    - pyqt
    - pyepics
    - pyyaml
    - numpy

build:
  noarch: python
  number: 5
  entry_points:
    - snapshot = snapshot.snapshot:main

about:
  home: https://github.com/paulscherrerinstitute/snapshot
  summary: "Tool to save and restore EPICS channels."
