package:
    name: snapshot
    version: 0.9.3
source:
#    git_tag: 0.9.1
#    git_url: https://git.psi.ch/cosylab/snapshot_tool.git
    path: ..

requirements:
    build:
        - python
        - setuptools
        - pyqt
    run:
        - python
        - pyqt

build:
  entry_points:
    - snapshot = snapshot.snapshot:main

about:
    home: https://github.psi.ch/cosylab/snapshot_tool
    summary: "Tool to save and restore EPICS channels."
