package:
  name: snapshot
  version: "{{ load_setup_py_data().version }}"
source:
  path: ..

requirements:
  build:
    - python
    - setuptools
    - pyqt
    - pyepics
  run:
    - python
    - pyqt
    - pyepics
    - pyyaml
    - numpy

build:
  noarch: python
  number: 0
  entry_points:
    - snapshot = snapshot.snapshot:main

about:
  license: GPL-3.0-or-later
  license_file: ../LICENSE
  home: https://github.com/paulscherrerinstitute/snapshot
  summary: "{{ load_setup_py_data().description }}"
  description: "{{ load_setup_py_data().description }}"
