
name: conda_publish

on:
  release:
    types: [published, edited]
  workflow_dispatch:
    
jobs:

  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # by default, it uses a depth of 1
          # this fetches all history so that we can read each commit
          fetch-depth: 0
      - name: Generate Changelog
        run: .github/release_message.sh > release_message.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: release_message.md

  publish:
    needs: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: publish-to-conda
      uses: paulscherrerinstitute/conda-publish-action@master
      with:
        subdir: 'conda-recipe'
        anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
        channel_opts: '-c conda-forge'
